name: C/C++ CI

on:
  push:
    branches: [ master, main, dev ]
  pull_request:
    branches: [ master, main, dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: nttld/setup-ndk@v1
      with:
        ndk-version: r21e
    - name: make
      run: ndk-build NDK_PROJECT_PATH=. APP_BUILD_SCRIPT=./Android.mk APP_PLATFORM=android-9
      
    - uses: actions/upload-artifact@v2
      with:
        name: workspace
        path: ./**/*
